# ========================
# GENERAL CONFIGURATION
# ========================
spring.application.name=CiberNext
server.port=${SERVER_PORT}

# Profile activo (local, docker, prod)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# ========================
# DATABASE CONFIGURATION
# ========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA / HIBERNATE CONFIG
# ========================
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true

#spring.sql.init.mode=never
#spring.sql.init.mode=always
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
#spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Configuracion del env�o de correos con Google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_SENDER_EMAIL}
spring.mail.password=${USER_SENDER_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ========================
# Configuracion del AbstractApi para validar un correo
# ========================
abstract.api.key = ${ABSTRACT_API_KEY}
abstract.api.url = ${ABSTRACT_API_URL}

# =========================
# SERVER CONFIGURATION
# =========================
debug=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
