# ========================
# GENERAL CONFIGURATION
# ========================
server.port=8080

# ========================
# DATABASE CONFIGURATION
# ========================
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/cibernextdb?createDatabaseIfNotExist=true
spring.sql.init.mode=always


# ========================
# JPA / HIBERNATE CONFIG
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ========================
# EMAIL CONFIGURATION
# ========================
spring.mail.username=officetotalfree@gmail.com
spring.mail.password=nsgv dxfm eeic bwxy


# ========================
# API CONFIGURATION
# ========================
abstract.api.key=8bc356ad13d84716a274e702698e3481
abstract.api.url=https://emailvalidation.abstractapi.com/v1/